<h2 id="brand-activation">Brand Activation</h2>
<p>The Brand Activation (or "Marketing Activities") serves multiple purposes. (1) To generate Brand Awareness, letting your target public know that you business exists. (2) Gaining the attention of prospective customers with an enticing Brand Perception. (3) Converting those prospective customers into paying clients. And, in some cases, you could include (4) customer retention, in other words, converting a one-time customer into a returning customer.</p>
<h3>1. Marketing Strategy</h3>
<p>There are different types of Marketing Strategies that can be applied to different businesses. However, for the purposes of this Framework we'll assume that this Marketing Strategy is aimed for a digitally-oriented business.</p>
<p>Additionally, this is a good time to make a distinction between the two types of Marketing Strategies. A few years ago, the trend for Marketers was to create ads on TV, radio, and print and essentially "yell" at a large target public sample hoping to gain the attention of some prospective customers, this approach is known as <strong>Outbound Marketing</strong>. On the other hand, with the rise of the internet, a new approach became the industry standard; <strong>Inbound Marketing</strong> focuses on stablishing valuable connections with your target public individually offering them useful content, more commonly in the form of an informative or entertaining social media post, blog post, email newsletter, eBook, videos, or other. A lot of educational information on Inbound can be found in <a href="https://academy.hubspot.com/" target="_blank">Hubspot Academy</a>.</p>
<p>This is also a great time to recommend the book <a href="https://www.goodreads.com/book/show/6150530-free" target="_blank">"Free: The Future of a Radical Price"</a>, which essentially prposes that on the internet age it's beneficial to entice customers by <strong>offering something of value for free</strong> in order to gain their attention and then convert some prospective customers into paying clients. This can be in the form of a free eBook, a trial of your product, or in the case of Poly Atlas, publishing this Wiki for free in order to maximize our Brand Awareness.</p>
<p>You should know that there are two types of reach that your media can have. <strong>Organic Reach</strong> is by default how your current social media followers would see your latest post, or how someone knowing your website's URL would enter directly. By comparisson, <strong>Paid Reach</strong> includes all Brand Communications that have been financially promoted to reach a larger public sample, including boosted social media posts or online ads.</p>
<p>Another important point, considering that content creation is the cornerstone of Inbound marketing, is that there are two types of content that you might create. <strong>Curated Content</strong> refers to all content that you have not created originally, but have shared in your Brand Communications; For instance, Retweeting a relevant tweet, sharing an Instagram post from someone else's account on your feed, or creating a blog post listing, for example, "The Best 10 Tools for Remote Work". On the other hand, <strong>Original Content</strong> refers to all the content that you have created originally for your Brand. Ideally, your Brand should generate both kinds of content. In order to cut through the noise of a busy newsfeed, your Brand should be generating content continuosly.</p>
<p>Lastly, what you must keep in mind, is that in the age of the internet, Marketing is <strong>a continuos practice performed in real time</strong>. Digital Marketing is not just about social media posts, but it should also include the aftermath of how you reply to comments, answer chat messages, or generating live content like an Instagram or YouTube live stream video.</p>
<p>Considering that Marketing is a continous practice and in real time, Marketers should <strong>continuosly test and measure results and optimize</strong> their practices to gain a larger Brand Awareness and a better Brand Perception.</p>
