<hr class="second-separator">
  <h2 id="getting-started">Getting Started</h2>
    <small>Description</small>
    <p>This framework can be a valuable resource for any person with an interest in Branding, whether you are a seasoned creative professional, a rookie design or marketing student, an entrepreneur or business owner, or simply a Branding enthusiast.</p>
    <p>Each section of <strong>this platform breaks down the Branding process into individual goals</strong> along with: (1) a general description of each goal, (2) an account of whom in the Branding team should be appointed to perform each task, (3) a rough estimation of the hours of work allocated to each goal, and (4) further information, resources, and case studies.</p>
    <p>Branding is a multidisciplinary process and hence it's best performed by a team of professionals who specialise on each discipline. However, whether you wish to design Brand Identities for clients as a part of a creative team or as a solo freelancer, following this framework —and, if necessary, adapting it to your specific needs— aims to <strong>(1) provide you with a better understanding of the Branding process,</strong> and <strong>(2) optimising and expediting your workflow,</strong> allowing you to fast-track all the minor administrative tasks and allowing you to focus your efforts on the creative output.</p>
    <p>All along this workflow you will find entries titled "The Poly Group" which showcase how we, at The Poly Group, have performed each task.</p>
    <p>However, bear in mind that <strong>every Branding or Brand Identity Design project is unique and can be vastly different</strong> depending on the specifics of the business, industry, budget, time frame, target public, and the skill level of the people involved, as well as their resources and preferred work methodology.</p>
    <p>All authored content within this document is distributed for free by <a href="http://mynameisboris.com" target="_blank">Boris Hrncic</a> &amp; <a href="http://thepolygroup.co" target="
      ">The Poly Group</a> under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.</p>
    <p>Furthermore, this is a collection of what we at <a href="http://thepolygroup.co" target="_blank">The Poly Group</a> consider to be the best practices in Branding, but other authors may digress.</p>
    <p>You can be a part of the conversation and share your comments and questions in <strong>our online community</strong> <a href="http://polyforum.org" target="_blank">Poly Forum</a>, a place to discuss branding, share tips and resources, ask questions, request feedback, and connect with other creatives around the world.</p>
    <p>Now, let's go ahead and get started!</p>
